### ISSUE TITLE
ClusterCovariance does not have a type parameter

### ISSUE THREAD

**Issue by junyuan-chen** [matthieugomez/Vcov.jl#1]
Is there a good reason why the type parameter of `ClusterCovariance` is removed after commit https://github.com/matthieugomez/Vcov.jl/commit/008bfe7fc70d3a3cbddf431feb4f2c53f3a29b15 ?

I thought having a type parameter is useful here as functions such as `Vcov.completecases` and `nclusters` are assuming some specific types of the field `clusters`. In the former case, `clusters` is a tuple of `Symbol`s; while in the latter case, `clusters` is a named tuple of `GroupedArray`s. With a type parameter, such assumptions can be explicitly incorporated into the method definitions.

(I could make a pull request on that if needed.)

**Comment by matthieugomez** [comment]
I think I did this to avoid excessive specialization (say on the name of
the arrays). I guess we could revert to a type parameter and add
`@nospecialize` in the arguments of the function.

**Comment by junyuan-chen** [comment]
Ok, I see. Then, maybe instead of only having one field that is sometimes names and sometimes names paired with arrays, we could have two fields with the first one always being a tuple of names and the second one being a tuple of `GroupedArray`s.
